title: Xlog2n-Blog
description: "I'm a passionate artist who loves to draw and create. Yes, I code so much that I hardly have time to draw."
author:
  name: "Xlog2n"
  email: "xlog2n@gmail.com"
  url: "xlog2n.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "xlog2n"
year : "2024"

